### ISSUE TITLE
Map file extensions to user-specified language

### ISSUE THREAD

**Issue by atifaziz** [SimonCropp/MarkdownSnippets#14]
## Problem

I am using [Pygments](http://pygments.org/) for code highlighting of fenced code blocks in Markdown. MarkdownSnippets uses the file extension as the language identifier so for C# this ends up being `cs`. Unfortunately, the [Pygments lexers list](http://pygments.org/docs/lexers/) says that the short names recognized for C# are `csharp` or `c#` and so my code blocks appear without highlighting. I imagine that other people may run into a similar problem so it would help to offer a way to map file extensions to a language identifier for custom scenarios. The use of file extension as the language identifier can be left as a default.

### Solution 1: Configuration File

A configuration file is used to list the desired mappings between source file extensions and target language identifiers. I would suggest using the [INI format](https://en.wikipedia.org/wiki/INI_file) for simplicity as the complexity/ceremony of JSON or XML feels unwarranted. An example configuration would look like this:

```ini
[md-code-languages]
csharp=.cs
```

Multiple extensions mapping to a single language identifier should be allowed as separate entries:

```ini
[md-code-languages]
csharp=.cs
csharp=.cshtml
```

The command-line tool will look for a file called `mdsnippets.ini` in the target directory, parse the `[md-code-languages]` section (using [Gini](https://github.com/atifaziz/Gini)?) into a dictionary of file extension to language identifier mappings and make it available for the remainder of processing.

### Solution 2: Command-Line Arguments

An alternative to solution 1 would be to allow file extension to language identifier mappings to be specified as optional command-line arguments in the form of `--md-code-language:csharp=.cs`. Multiple such arguments could be supplied, one for each mapping.

**Comment by SimonCropp** [comment]
i would prefer having a config file. that way people can check that in.

And i would prob go with yaml

thoughts?

**Comment by atifaziz** [comment]
> i would prefer having a config file. that way people can check that in.

You can check-in a shell script that contains the command-line invocation, serving somewhat then as a poor man's configuration. The downside, I'll admit, over a configuration file is that data formats are more portable than shell scripts. At the same time, relying on command-line arguments means you don't have to debate about the configuration file format and most command-line usage seems to be standardising on POSIX guidelines these days (e.g. even Windows users are getting used to `--option` vs `/option`). In fact, if we go with _response files_ then command line arguments on their own _become_ the configuration and those _response files_ can be checked-in!

I would recommend starting with command-line arguments with response file support (which by the way, [System.CommandLine has added](https://github.com/dotnet/command-line-api/pull/80)). If an argument starts with `@` (convention) then the remainder of the argument string identifies the response file path. The response file should be read and contents inserted into the command line for further processing. A user should be able to specify more than one response file.

The command-line application could look for a _default response file_ named `mdsnippets.rsp` and if it exists then use it. This would help to keep `mdsnippets` invocations simple as just invoking the tool on a project directory.

If you still want to offer a configuration, in YAML or INI, then it can be added later but my guess is that with the above approach, “you ain't gonna need it”.

With command-line + response files, one has maximum flexibility. If I want to test a setting of MarkdownSnippet, I can just invoke it with the corresponding command-line argument to test the desired effect. With a configuration file as the sole driver of behaviour, I have to modify the configuration file, have the source control system see that as a change and revert later to undo.

**Comment by SimonCropp** [comment]
ok i am happy to go with command line arguments.

**Comment by SimonCropp** [comment]
@atifaziz is it not possible to inherent from the existing c# lexer and add an extra extension? http://pygments.org/docs/lexerdevelopment/#subclassing-lexers-derived-from-regexlexer

**Comment by atifaziz** [comment]
@SimonCropp Thanks, that could work but felt like an overkill as I don't need a custom lexer per se.

**Comment by SimonCropp** [comment]
Is it possible to add an extra alias to an existing lexer in pygments?

Also doesnt it seem strange the c# lexer does not have .cs as an alias already?

**Comment by SimonCropp** [comment]
any more progress ?
