### ISSUE TITLE
Snippet source link customization

### ISSUE THREAD

**Issue by atifaziz** [SimonCropp/MarkdownSnippets#15]
## Problem

There is no way to customize the `[snippet source]` link, such as:

- omit it from the output Markdown document
- specify an alternate URL prefix for when they are hosted elsewhere than the documentation

## Solution

Add command-line arguments or configuration (not unlike the suggestions in #14) to:

- disable the snippet source link altogether
- specify a URL prefix such

The URL prefix should recognize a token such as `$`, which when present, is replaced with the commit hash. This provides a more stable link from the documentation to the snippet, in case the latter changes or moves.

**Comment by SimonCropp** [comment]
yep no complaints here. happy to accept PRs for any of those

**Comment by atifaziz** [comment]
I think this would require command-line support for customization, like discussed in #14. How's the spike coming along in the [`CommandLineExperimental`](https://github.com/SimonCropp/MarkdownSnippets/tree/CommandLineExperimental) branch?

If that's too experimental for now, I can suggest starting simply. [NDesk.Options](http://www.ndesk.org/Options) (there's also a [NuGet package](https://www.nuget.org/packages/NDesk.Options/)), which has been around for ages, has served me pretty well. I can submit a PR with some initial command-line handling support if you'd welcome that. One can always migrate away to [System.CommandLine](https://github.com/dotnet/command-line-api) once it's more stable and usable.

**Comment by SimonCropp** [comment]
@atifaziz i pushed some command line parsing code to master. should be enough to build on if u want to do a PR

**Comment by SimonCropp** [comment]
so the git hash would be passed in as a command argument?

**Comment by atifaziz** [comment]
> so the git hash would be passed in as a command argument?

I'm thinking just some URL prefix so shouldn't matter if it contains a Git hash or not.

**Comment by SimonCropp** [comment]
Could use this https://github.com/SimonCropp/MarkdownSnippets/blob/master/src/MarkdownSnippets/GitHashReader.cs

**Comment by atifaziz** [comment]
I see you've added [a new feature enabling `*.source.md` files to be hosted in a separated directory](https://github.com/SimonCropp/MarkdownSnippets/blob/872f29fc622fc71d26b6856d57a9185cd5084aea/readme.md#mdsource-directory-convention). I needed customization proposed in this issue because I precisely had that same layout. Let me re-evaluate things in light of the new changes (been away on vacation for the last two weeks) and come back to you.

**Comment by SimonCropp** [comment]
@atifaziz any more thoughts on this?

**Comment by atifaziz** [comment]
Sorry but none yet. I haven't had the chance to return to the project when I am using this.

**Comment by SimonCropp** [comment]
bump :)

**Comment by atifaziz** [comment]
@SimonCropp Sorry for giving you the silent treatment on this and on #14 but I did try and reach out to you on Twitter by DM for a quick chat but never got a response; I figured you got busy too. Anyway, closing this and #14 is the right call for now because I haven't gotten [any feedback or contributions](https://github.com/morelinq/MoreLINQ/issues/189) in my [MoreLINQ](https://github.com/morelinq/MoreLINQ) project where I planned to use MarkdownSnippets so I've left a [version of docs](https://github.com/morelinq/examples) out there based on [Try .NET](https://github.com/dotnet/try). If activity picks up and there's direction that nudges towards MarkdownSnippets then I'll revert and pick this up.

**Comment by SimonCropp** [comment]
> I did try and reach out to you on Twitter by DM for a quick chat but never got a response; 

So sorry. i must have missed that.

And yep trivial to re-open this in the future. i might get to it myself eventually
