### ISSUE TITLE
Way to pull in files from outside repo - preferably by supplying a URL to text file

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#157]
#### Is the feature request related to a problem

No.

I would like to pull in to docs some files that, for C++-builds-reasons, cannot be in my repo: they are in another repository that is adjacent to mine.

I tried these things:

**1. Add a snippet to pull the file in via relative links:**

`snippet: ../../../ApprovalTests.cpp.CMakeSamples/develop_approvaltests/CMakeLists.txt`

Result:

`Failed: Missing snippets: ../../../ApprovalTests.cpp.CMakeSamples/develop_approvaltests/CMakeLists.txt`

**2. Added a symlink to the adjacent repo, so it appears to be inside my repo**

```bash
ln -s /Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp.CMakeSamples .
```

Then put this snippet in:

`snippet: develop_approvaltests/CMakeLists.txt`

(t needs a directory, because there are CMakeLists.txt files in many directories)

Result:

```
Added 697 .source.md files
Searching 17720 files for snippets
Unhandled exception. System.IO.IOException: Too many levels of symbolic links
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at MarkdownSnippets.FileSnippetExtractor.Read(String path, Int32 maxWidth) in C:\projects\markdownsnippets\src\MarkdownSnippets\Reading\FileSnippetExtractor.cs:line 95
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MarkdownSnippets.DirectoryMarkdownProcessor.AddSnippetsFrom(String directory) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 101
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, Boolean scanForMdFiles, Boolean scanForSnippets, Action`1 log, AppendSnippetGroupToMarkdown appendSnippetGroup, Boolean writeHeader, String header, DirectoryFilter directoryFilter, Boolean readOnly, LinkFormat linkFormat, Int32 tocLevel, IEnumerable`1 tocExcludes, Boolean treatMissingSnippetsAsWarnings, Int32 maxWidth, String urlPrefix) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 71
   at Program.Inner(String targetDirectory, ConfigInput configInput) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\Program.cs:line 28
   at CommandRunner.<>c__DisplayClass0_0.<RunCommand>b__0(Options options) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\CommandRunner.cs:line 41
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at CommandRunner.RunCommand(Invoke invoke, String[] args) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\CommandRunner.cs:line 42
   at Program.Main(String[] args) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\Program.cs:line 11
./run_markdown_templates.sh: line 15: 14890 Abort trap: 6           mdsnippets --exclude cmake-build:build --toc-level 5 --readonly true --header "GENERATED FILE - DO NOT EDIT\nThis file was generated by [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets).\nSource File: {relativePath}\nTo change this file edit the source file and then execute ./run_markdown_templates.sh."
```

**3. Try a URL instead**

This was kind of wishful thinking - and not actually the file I wanted to include - but as an experiment:

`snippet: https://github.com/approvals/ApprovalTests.cpp.Qt.StarterProject/blob/master/CMakeLists.txt`

Result:

```
Failed: Missing snippets: https://github.com/approvals/ApprovalTests.cpp.Qt.StarterProject/blob/master/CMakeLists.txt
```

#### Describe the solution

> A clear and concise proposal of how you intend to implement the feature.

Sorry, I don't know C# so won't be able to do this.

If it were possible to implement any of these:

* Allow relative links to outside the repo
* Allow symlinks inside the repo, to repos elsewhere
* Allow hyperlinks and embed their content

I prefer the last one, as mdsnippets would presumably not need to work out repo URLs - it could just use the exact URL that was supplied...

Another reason for preferring the last one is that anyone else could run mdsnippets on this project without having to clone the other repo in a particular location, and possible even create a symlink to it.

#### Describe alternatives considered

> A clear and concise description of any alternative solutions or features you've considered.

I'm going to have to copy-and-paste the source files in.

#### Additional context

> Add any other context about the feature request here.

There is an additional problem in this case, which is that these CMakeLists.txt files will need to be formatted with the "cmake" language, which isn't obvious from the file extension...

For example:

```cmake
cmake_minimum_required(VERSION 3.14 FATAL_ERROR)
# This version is needed for FetchContent_Declare & FetchContent_MakeAvailable

project(fetch_content_approvaltests)

enable_testing()

add_subdirectory(dependencies)
add_subdirectory(tests)
```

**Comment by SimonCropp** [comment]
would UrlsAsSnippets work for you? https://github.com/SimonCropp/MarkdownSnippets#urlsassnippets  https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md

**Comment by claremacrae** [comment]
I think so - thank you!

I'll try them out...

**Comment by claremacrae** [comment]
I think so - thank you!

I'll try them out...

**Comment by claremacrae** [comment]
Hi Simon,

Is there any way that I can set the markdown format of the included file to `cmake`, please?

I tried it out anyway, and I'm probably missing something obvious but I can't see from experimenting, and from the docs, how I include the url snippet...

Here's what I tried:

```json
{
  "ReadOnly": true,
  "TocLevel": 5,
  "Exclude": [ "cmake-build", "build" ],
  "UrlsAsSnippets": [
    "https://raw.githubusercontent.com/Fody/Fody/master/FodyPackaging/Weaver.props",
    "https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/master/add_subdirectory_approvaltests_catch2/dependencies/CMakeLists.txt"],
  "TocExcludes": [ "Exclude Heading1", "Exclude Heading2" ],
  "WriteHeader": true,
}
```

Then first attempt:

```markdown

snippet: https://raw.githubusercontent.com/Fody/Fody/master/FodyPackaging/Weaver.props
```

Result:

Failed: Missing snippets: https://raw.githubusercontent.com/Fody/Fody/master/FodyPackaging/Weaver.props

Next attempt:

```markdown
include: https://raw.githubusercontent.com/Fody/Fody/master/FodyPackaging/Weaver.props
```

Result:

** Could not find include 'https://raw.githubusercontent.com/Fody/Fody/master/FodyPackaging/Weaver.props.include.md' **

**Comment by claremacrae** [comment]
Hi Simon,

Searching through GitHub, I found out how to get this working...

With this:

```
  "UrlsAsSnippets": [
    "https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/master/develop_approvaltests/CMakeLists.txt"
  ],
```

I was able to get this to work:

```
snippet: CMakeLists.txt
```

Because I'd like to include several different CMakeLists.txt URLs, I tried this - and it didn't find the snippet.

```
snippet: develop_approvaltests/CMakeLists.txt
```

**Comment by claremacrae** [comment]
Realistically, I suggest closing this issue...

I think it would need to many highly specific features that probably very few users would need.

So I've written a [script to find the files from the other repo, and convert them to mdsnippets include files](https://github.com/claremacrae/ApprovalTests.cpp.CMakeSamples/blob/5b53b4a6d26beac76225d0cc4792cf4a52d5aff4/create_markdown.py).

The included files won't change very often after the initial setup, so it's good enough for now...

**Comment by claremacrae** [comment]
PS But thanks for pointing out UrlsAsSnippets - when names in URLs are unique, and file extensions are helpful, it's useful to know about...

**Comment by SimonCropp** [comment]
i think i can make this work better. gimme a day

**Comment by claremacrae** [comment]
OK, thank you very much! I was just about to work on a PR to make the docs say how to use a URL snippet, but I'll wait...

**Comment by claremacrae** [comment]
I feel this is cheeky to suggest, but just in case:

Wishful thinking: it might be useful for URL snippets to link to sources, just as the ordinary ones do...

**Comment by claremacrae** [comment]
Feel free to ignore these comments, of course... I'm adding them in case they are helpful...

What if users didn't need to add the URLs in the config, and could put URLs straight in to the markdown:

snippet: https:/....

That would make writing docs DRYer.

**Comment by SimonCropp** [comment]
can u try 18.0.0-beta.2

**Comment by claremacrae** [comment]
Sure - how do I find out what to test? How it works now?

**Comment by SimonCropp** [comment]
i think i implemented how you requested?

https://github.com/SimonCropp/MarkdownSnippets#including-urls

https://github.com/SimonCropp/MarkdownSnippets#including-urls-1

**Comment by claremacrae** [comment]
Ah right - thank you. I was looking in the section "UrlsAsSnippets", based on looking for 'URL' in the table of contents, and didn't notice those other additions....

Yes it works great - and for cases where the URL file extension matches the markdown formatting I want, I'll definitely use it.

Thanks very much for doing this!

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
