### ISSUE TITLE
Is it intentional that there is no error message for missing includes?

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#158]
Markdown .source.md:

```markdown
include: sdfafasdfa
```

where `sdfafasdfa.include.md` does not exist.

After running mdsnippets '17.7.2', there is now error message...

Where `snippets:` are missing, there's a helpful fatal error.

**Comment by claremacrae** [comment]
I now see that there is an error message in the generated Markdown, which helps:

```markdown
** Could not find include 'sdfafasdfa.include.md' **
```

So for clarification, I was thinking about error messages on the command line...

Since we review differences, I think the error in the output file is livable with, to minimise work on this project, if you prefer!

**Comment by SimonCropp** [comment]
yep this should throw by default. i will fix it

**Comment by SimonCropp** [comment]
i deployed a new beta that should fix this
