### ISSUE TITLE
MSBuildTask does not play well with NCrunch

### ISSUE THREAD

**Issue by damianh** [SimonCropp/MarkdownSnippets#175]
#### Describe the bug

To be honest I don't think it's a bug really but reporting this as an FYI for you and others so close immediately :)

When using the MSBuild task and NCrunch is running then one receives a compilation error from ncrunch:

`..\..\..\..\..\Users\damian\.nuget\packages\markdownsnippets.msbuild\17.6.0\build\MarkdownSnippets.MsBuild.targets (21, 6): No '.git' directory found. Define a 'MdTargetDir'`.

The reason is that NCrunch copies things to workspace directory that obviously won't be a git repo. I'm not sure setting the `MdTargetDir` will suffice as MSBuild variables will be pointing to workspace directory instead of the repo directory.

In anycase I'll switch over to the dotnet tool.

#### Minimal Repro

1. Checkout [this commit].
2. Enable ncrunch.

**Comment by SimonCropp** [comment]
this is a bug. i will fix it

**Comment by damianh** [comment]
(Fixed typo's. I should proof-read more often.)

**Comment by SimonCropp** [comment]
can u try the current version?

**Comment by damianh** [comment]
🤦‍♂ I should have mentioned the version and checked the newer one.

v18.0.0 doesn't exhibit the behaviour. I see the fix here: https://github.com/SimonCropp/MarkdownSnippets/commit/ccb6a754a5c17812af039df5c2f1b1b9139163da

Sorry for time wasting 😞

**Comment by SimonCropp** [comment]
no worries
