### ISSUE TITLE
Allow other files than text files

### ISSUE THREAD

**Issue by joshkel** [SimonCropp/MarkdownSnippets#21]
```
snippet: tests/approvals/ApprovalTest.testVerifyAsJson.approved.json
```

results in

> Failed to process markdown: Missing snippets: tests/approvals/ApprovalTest.testVerifyAsJson.approved.json

This does not happen if we use a `.txt` file.

Thank you,
Josh and Llewellyn

**Comment by SimonCropp** [comment]
can u try 9.1.2
