### ISSUE TITLE
MdTargetDir .git error

### ISSUE THREAD

**Issue by jzabroski** [SimonCropp/MarkdownSnippets#251]
#### Preamble
Using MarkdownSnippets.MSBuild 18.0.0 or 19.0.0 - same error

#### Describe the bug

*A clear and concise description of what the bug is. Include any relevant version information.*
It seems like MarkdownSnippets.MSBuild is not usable when the initial build target is `dotnet test`.

*A clear and concise description of what you expected to happen.*
A clearer error message than:

> No '.git' directory found. Define a `MdTargetDir`.

*Add any other context about the problem here.*
I reviewed the last code change, here: https://github.com/SimonCropp/MarkdownSnippets/commit/fee9f9b62c42d8ab685a273814ec096251b5d317#r40062164

#### Minimal Repro

Clone RazorLight repo.  run the following commands in root directory:

```powershell
dotnet --info
dotnet restore
dotnet test  tests/RazorLight.Tests/RazorLight.Tests.csproj
```

**Comment by jzabroski** [comment]
The problem seems to be that it assumes you'll always run `dotnet test` without any csproj argument, and that your solution directory is tightly coupled to your `.git` directory.  Is there a way to configure this?  I don't see anything in the readme.

**Comment by SimonCropp** [comment]
can u try 19.0.1

**Comment by jzabroski** [comment]
Seems to be fixed.
