### ISSUE TITLE
"More Info" links on "Config File" page 404

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#262]
#### Describe the bug

View this:

https://github.com/SimonCropp/MarkdownSnippets/blob/ee19cf65031efffdc5e240a72d9d1ea7cf1a6461/docs/config-file.md

Click on each of the links in "More Info" section at the end...

For me, all give 404s...

I'll try a PR later on...

**Comment by SimonCropp** [comment]
@claremacrae sorry for the hassle. this is now fixed

**Comment by claremacrae** [comment]
No apology needed - thanks for fixing this, Simon!
