### ISSUE TITLE
Add ability to process other document extensions

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/MarkdownSnippets#268]
defined by DocumentExtensions in config https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md

**Comment by claremacrae** [comment]
I read the docs from this - and after two readings, I still can't work out what the feature is.

It says "process" other docs - but what kind of processing? A little more description to say what it is, and why one might use it. would be helpful...

**Comment by SimonCropp** [comment]
@claremacrae @jawn does this answer your question https://github.com/SimonCropp/MarkdownSnippets#documentextensions  ?
