### ISSUE TITLE
Feature request: Additional option for the lib to work on a single file rather than source and generated file

### ISSUE THREAD

**Issue by mysticmind** [SimonCropp/MarkdownSnippets#273]
#### Problem at hand

- With the current functionality, it requires 2 files to be maintained i.e `file.source.md` with the snippet markers and the tool generates `file.md` with the snippet content.
- For some use cases such as Github readme files or in general, it is a bit cumbersome and convoluted to maintain source and generated files in source code control. Also this requires clear documentation and instructions in projects for contributors to only edit the source file and not the generated one.

#### Proposed solution

- Given that the source file has markers `snippet: name` and the generated file has content within `<!-- snippet: name -->` and `<!-- endsnippet -->`. It is quite easy to detect the snippet content block based on these 2 patterns without any ambiguity and replace with the generated snippet on the same file. 

My request is to add an option for the tool to work on a single file based on these patterns.

**Comment by SimonCropp** [comment]
ok. i will have this done in a couple of days

**Comment by SimonCropp** [comment]
hows this https://github.com/mysticmind/reversemarkdown-net/pull/81 ?

**Comment by SimonCropp** [comment]
https://github.com/SimonCropp/MarkdownSnippets#inplaceoverwrite

**Comment by mysticmind** [comment]
Thanks @SimonCropp, this will be really helpful feature.

**Comment by claremacrae** [comment]
I've had a go at using on some of the files in [ApprovalTests.cpp](https://github.com/approvals/ApprovalTests.cpp)...

I'll update this as I go, but the pattern for updating seems to be:

* Make sure you have updated to the beta
  * `dotnet tool update --version 20.0.0-beta.3 -g MarkdownSnippets.Tool`
* Rerun the tool and commit the .md files (lots of changes such as `endtoc` -> `endToc`)
* Delete all your .source.md files
* Change your `mdsnippets.json` file
  * See https://github.com/approvals/ApprovalTests.cpp/commit/5091ab39e757f1df05635a88592aa363f23170d4
  * Unfortunately CLion auto-formatted which makes the diffs harder to see
  * The changes were:
    * Turn off ReadOnly
    * Remove WriteHeader line entirely
    * Add `"Convention": "InPlaceOverwrite"`

These changes are on the [mdsnippet_inplace](https://github.com/approvals/ApprovalTests.cpp/tree/mdsnippet_inplace) branch

**Comment by claremacrae** [comment]
Problem 1: mdsource/include_blah.include.md files are not found:

Error message:

```
Processing /Users/clare/Documents/develop/ApprovalTests/ApprovalTests.cpp/doc/UsingGoogleTests.md
Failed: Missing includes: include_ninja_warning_note.
```

Original line in generated .md file:

```
**Note:** Approval Tests has some specific build requirements if it is built with the [Ninja build generator](https://ninja-build.org/). **If you use Ninja with Approval Tests, special care is needed when setting up builds**, to avoid compilation errors or test failures. If you have any problems with this, please see [Troubleshooting Misconfigured Build](/doc/TroubleshootingMisconfiguredBuild.md#top). <!-- singleLineInclude: include_ninja_warning_note. path: /doc/mdsource/include_ninja_warning_note.include.md -->
```

**Comment by claremacrae** [comment]
**Problem 2: https includes not found**

Console output:

`Failed: Missing includes: https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/fetch_content_approvaltests/mdsource/inc_fetch_content_approvaltests_cmakelists.include.md., https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/fetch_content_approvaltests/mdsource/inc_fetch_content_approvaltests_tests_cmakelists.include.md., https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/fetch_content_approvaltests_catch2/mdsource/inc_fetch_content_approvaltests_catch2_dependencies_cmakelists.include.md., https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/fetch_content_approvaltests/mdsource/inc_fetch_content_approvaltests_dependencies_cmakelists.include.md., https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/add_subdirectory_approvaltests_catch2/mdsource/inc_add_subdirectory_approvaltests_catch2_dependencies_cmakelists.include.md., https://raw.githubusercontent.com/claremacrae/ApprovalTests.cpp.CMakeSamples/main/develop_approvaltests/mdsource/inc_develop_approvaltests_cmakelists.include.md.`

**Comment by claremacrae** [comment]
Probably you've done this alreadyy, @SimonCropp, but if the project's tests don't already test that all generated text can be round-tripped (regenerated consistently from inside a generated file), maybe that would be a good thing to build in to the tests automatically now, to ensure this keeps working for all future new features - and existing features that I haven't just tested...
