### ISSUE TITLE
Git reports spurious change on Mac for file with toc and no headings

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#309]
Hi Simon,

This is a scenario that I didn't think of with #288.

I've started getting diffs showing up in CLion when I run mdsnippets, but git says that there are no changes to check in.

Eventually I used a different diff tool, and this is what I see - on the left is the output from mdsnippets, and on the right is the file in GitHub:

![image](https://user-images.githubusercontent.com/4840096/94747865-e00ef400-0377-11eb-98bc-21b0029fb480.png)

The adding of a placeholder for an empty toc includes a windows EOL, although I am running on Mac.

Would it be possible for the empty toc code to be changed to write a native EOL please?

**Comment by SimonCropp** [comment]
can u try 21.1.3

**Comment by claremacrae** [comment]
> can u try 21.1.3

Yes, updating from '21.0.7' to version '21.1.4' fixed it - thanks very much Simon!

**Comment by SimonCropp** [comment]
@claremacrae WIN 👍
