### ISSUE TITLE
GitHubMarkdownProcessor.RunForFilePath() was removed w/o any traces of what replaces it

### ISSUE THREAD

**Issue by SeanFeldman** [SimonCropp/MarkdownSnippets#31]
Version 10 has removed `GitHubMarkdownProcessor.RunForFilePath()` that was needed to regenerate documentation w/o hints/traces what replaces it.

[API usage section](https://github.com/SimonCropp/MarkdownSnippets/tree/master#api-usage) targets v10 which seems way more than v9 used to have, with no migration info.

Update: [Running as unit test section](https://github.com/SimonCropp/MarkdownSnippets#running-as-a-unit-test) has this change, but I didn't notice the subtle difference in the name.

**Comment by SeanFeldman** [comment]
`GitHubMarkdownProcessor` has become `DirectoryMarkdownProcessor`.
@SimonCropp would be nice if MarkdownSnippets use `ObsoleteEx` to let know about the change.

**Comment by SimonCropp** [comment]
good point. added an obsolete in 10.0.1 and added an issue regarding that change to the v10 milestone https://github.com/SimonCropp/MarkdownSnippets/issues/32

**Comment by SeanFeldman** [comment]
Thank you @SimonCropp
