### ISSUE TITLE
21.7.0 is not compatible with netcoreapp3.1 

### ISSUE THREAD

**Issue by LarsEckart** [SimonCropp/MarkdownSnippets#331]
Hello Simon,

in Approvaltests.Java we run MarkdownSnippets as part of the Github Actions on new commits.

[Here](https://github.com/approvals/ApprovalTests.Java/runs/1383816170?check_suite_focus=true) it is installing version 21.6.1 and succeeding, couple of days later [here](https://github.com/approvals/ApprovalTests.Java/runs/1408716495?check_suite_focus=true) it tries to install version 21.7.0 and does not succeed any more.

I'm sadly not very familiar with .NET core to understand where this incompatibility is coming from or what to do. We're already using windows-latest as environment for this github action. 

Is .NET core 3.1 old and we should perhaps tell the github action to update it before using dotnet tool to install MarkdownSnippets?

**Comment by SimonCropp** [comment]
sorry for the hassle. so this should work OOTB when GH Actions moves to net5. unfortunately that situation is a bit of a mess right now https://github.com/actions/virtual-environments/issues/2022 https://github.com/actions/virtual-environments/issues/1891

for now i will pin mdsnippets in Approvaltests org to v 21.6.1 https://github.com/approvals/ApprovalTests.Java/commit/7e11c0d44409510548681cc23e7f03d8c1dd3a84

**Comment by SimonCropp** [comment]
> Is .NET core 3.1 old and we should perhaps tell the github action to update it before using dotnet tool to install MarkdownSnippets?

that is an option, but it would significantly slow down you build
