### ISSUE TITLE
include markdown file adds comments in the first line which can break markdown rendering

### ISSUE THREAD

**Issue by LarsEckart** [SimonCropp/MarkdownSnippets#337]
Given:
include: PairWiseTest.forTable.approved

with:
```
| Number of Parameters | Variations per Parameter | Total Combinations | Pairwise Combinations |
| -------------------- | ----------------------- | ------------------ | --------------------- |
|2|5|25|25|
```

we get:
```
| Number of Parameters | Variations per Parameter | Total Combinations | Pairwise Combinations | <!-- include: PairWiseTest.forTable.approved. path: /approvaltests-tests/src/test/java/org/approvaltests/combinations/PairWiseTest.forTable.approved.include.md -->
| -------------------- | ----------------------- | ------------------ | --------------------- |
|2|5|25|25|
```

which renders as 
| Number of Parameters | Variations per Parameter | Total Combinations | Pairwise Combinations | 
| -------------------- | ----------------------- | ------------------ | --------------------- |
|2|5|25|25|

instead of 

| Number of Parameters | Variations per Parameter | Total Combinations | Pairwise Combinations | 
| -------------------- | ----------------------- | ------------------ | --------------------- |
|2|5|25|25|

The fix for this should be that the comment occurs before any of the text, instead of after the first line.

Thanks

Lars & Llewellyn

**Comment by LarsEckart** [comment]
our current work around was to include two line breaks at the beginning of the file.

**Comment by SimonCropp** [comment]
can u try 21.7.1

**Comment by LarsEckart** [comment]
hmm, I'm not sure we can since it looks like the issues you linked https://github.com/SimonCropp/MarkdownSnippets/issues/331 are still not resolved.

**Comment by SimonCropp** [comment]
a little confuses. i linked to 337.

**Comment by SimonCropp** [comment]
BTW what repo are you using this in?

**Comment by LarsEckart** [comment]
in ApprovalTests.Java
appeared after using include here: https://github.com/approvals/ApprovalTests.Java/commit/402c637cb1f6220c21551383977a33e2036ea0ff 
and fix commit https://github.com/approvals/ApprovalTests.Java/commit/8c4f3f62b1c621a9901700d7883bd0f26baa8b1e

**Comment by LarsEckart** [comment]
I can confirm that the update resolves our issue. We'll remove the work around once we can use 21.7.1 in GitHub Actions.
