### ISSUE TITLE
Could we provide better help for a confusing error message

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#354]
#### Preamble

The error message `Failed: Could not derive new-line string from markdown files.` could be improved to help users solve the underlying problem.

#### Describe the bug

Summary: if no .source.md or .md files (depending in `Convention`) are found, the error message given doesn't really guide users to solve the underlying configuration problem:

`Failed: Could not derive new-line string from markdown files.`

----

Pairing on ApprovalTests.python today, and starting to implement markdown snippets, our first few builds had this error [in the logs](https://github.com/approvals/ApprovalTests.Python/runs/1717567014?check_suite_focus=true#step:3:42):

```
Config:
    RootDir: D:\a\ApprovalTests.Python\ApprovalTests.Python
    UrlPrefix: 
    LinkFormat: GitHub
    Convention: SourceTransform
    TocLevel: 2
    ValidateContent: False
    HashSnippetAnchors: False
    TreatMissingAsWarning: False
    FileConfigPath:  (exists:False)
    ReadOnly: False
    WriteHeader: 
    Header:
Failed: Could not derive new-line string from markdown files.
Error: Process completed with exit code 1.
```

The message "Could not derive new-line string from markdown files." is from [DirectoryMarkdownProcessor.cs#L166](https://github.com/SimonCropp/MarkdownSnippets/blob/636030308e73bd2a009489f4de493aae85c9044a/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs#L166)

We eventually worked out that:

*  the problem was that we hadn't provided a config file
*  so we were missing a `"Convention": "InPlaceOverwrite"` line
* so mdsnippets was looking for `*.source.md` files
* it didn't find any matching files - so couldn't work out the line-endings currently used.

This could happen in the above situation, or less-likely - if there were no .md files present in the directory at all... which might be possible if run in the wrong working directory.

#### Minimal Repro

Run mdsnippets in a directory with no .source.md files and no mdsnippets.json file.

#### Submit a PR that fixes the bug

I did just update my fork, and start work on improving the message, but it became so verbose that I thought it better to have a chat about it first....

Something like this: ☹️ 

```c#
            throw new SnippetException("Could not derive new-line string from markdown files. Check your working directory. Check that the directory contains at least one .md or .source.md, depending on whether you are doing an in-place conversion. See https://github.com/SimonCropp/MarkdownSnippets#inplaceoverwrite");
```

It might be better to specifically detect whether any source files have been found, and if not, put a more specific source message at that point???

**Comment by SimonCropp** [comment]
how about instead of an error message we just default to `\n` if we cant find any files?

**Comment by isidore** [comment]
yes, that's good, but I would also say it might be useful to error if there are no files found which are viable candidates for MD snippets.

**Comment by SimonCropp** [comment]
can u try 22.0.2

**Comment by claremacrae** [comment]
> yes, that's good, but I would also say it might be useful to error if there are no files found which are viable candidates for MD snippets.

Yes... I think that's the most likely mode of failure: new user runs mdsnippets in a repo with only .md files, not .source.md - and doesn't know that they need to supply the in-place-overwrite option...

A message that helped people understand what to do in that situation - even if just linking to a sectioning he online docs - would be ideal....

**Comment by SimonCropp** [comment]
yep those changes should be in 22.0.2

**Comment by claremacrae** [comment]
Thanks Simon... The output I see now is great:

```
Found 124 files for snippets
Failed: No markdown files found. This may be due to the DocumentConvention being SourceTransform.
See https://github.com/SimonCropp/MarkdownSnippets#document-convention
To move to InPlaceOverwrite add a file named `mdsnippets.json` in the target directory that contains:
{
  "Convention": "InPlaceOverwrite"
}
```

This is a huge improvement, thank you!

A couple of thoughts...

* Without extra knowledge, I wouldn't have known what you meant by "target" directory... Maybe "in the project's root directory"?
* Annoyingly, GitHub's rendering of URLs in to docs no longer jumps to anchors... This has been the case for some weeks now, at least... So that means that people have scroll down the `#document-convention` section - but I don't think there's anything you can do about that ...

**Comment by SimonCropp** [comment]
@claremacrae can u try 22.0.3

**Comment by claremacrae** [comment]
> @claremacrae can u try 22.0.3


The output is now:

```
To move to InPlaceOverwrite add a file named `mdsnippets.json` in the target directory (C:\Code\ApprovalTests.Python) that contains:
```

I see it includes the directory - and also that "target directory" is a phrase used throughout the docs in this project - so this is great, thank you!
