### ISSUE TITLE
```cs not supported by pygments.  Use ```c# is

### ISSUE THREAD

**Issue by drewburlingame** [SimonCropp/MarkdownSnippets#430]
Note: New issues raised, where it is clear the submitter has not read the issue template, are likely to be closed with "please read the issue template". Please don't take offense at this. It is simply a time management decision. If someone raises an issue, and can't be bothered to spend the time to read the issue template, then the project maintainers should not be expected to spend the time to read the submitted issue. Often too much time is spent going back and forth in issue comments asking for information that is outlined in the issue template.

If you are certain the feature will be accepted, it is better to raise a [Pull Request (PR)](https://help.github.com/articles/about-pull-requests/).

If you are uncertain if the feature will be accepted, outline the proposal below to confirm it is viable, prior to raising a PR that implements the feature.

Note that even if the feature is a good idea and viable, it may not be accepted since the ongoing effort in maintaining the feature may outweigh the benefit it delivers.

#### Is the feature request related to a problem

I'm looking to use this tool for managing snippets in CommandDotNet.  We're using mkdocs with the Pygments formatter.  There pygments.lexers.dotnet.CSharpLexer looks for ```c# or ```csharp.  ```cs results in no formatting being applied.  

#### Describe the solution

Output ```c# instead of ```cs for c# files, or provide a configuration to change the output for a language

#### Describe alternatives considered

this script in git bash is a viable workaround that I'll use in the meantime.

`find ./docs/ \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/```cs/```c#/g'`

Given there's a workaround, perhaps it's easier to document it and move on.  Thought I'd mention it regardless.

**Comment by drewburlingame** [comment]
created this issue with pygments.  https://github.com/pygments/pygments/issues/1962  It would be ideal to fix there if possible.

**Comment by SimonCropp** [comment]
yeah i can fix this here. give me a couple of days to get to it

**Comment by drewburlingame** [comment]
fyi, they've fixed it in pygments and the fix should b released by end of year. i can get by with the bash script until then so we can close this if you'd like.
