### ISSUE TITLE
mdsnippets adds a newline to the end of every file

### ISSUE THREAD

**Issue by drewburlingame** [SimonCropp/MarkdownSnippets#431]
#### Describe the bug

using 
- mdsnippets 24.2.0+49a8b7f7e522f8c32d351d97663e97e12722b82c
- Windows10
- git bash

The command used

`mdsnippets -c InPlaceOverwrite --url-prefix "https://github.com/bilal-fazlani/commanddotnet/blob/master"`

Most of my md files do not have end with a newline. eg.

![image](https://user-images.githubusercontent.com/103345/142604295-c0985680-74d7-4083-95cf-6a775ffd6273.png)

But after running mdsnippets, newline is added to the end of every file

![image](https://user-images.githubusercontent.com/103345/142604597-0a2683b0-973d-45a7-a28d-0e4fc3a2bc2b.png)

It **does not** add newline to files that already end with newline

It **does** add newline to every file, not just the files that will have snippets injected

#### Minimal Repro

Run mdsnippets with md files that do not end with newline

#### Submit a PR that fixes the bug

I haven't investigated where the fix should be yet.  Do you have a sense of where I should look?

**Comment by SimonCropp** [comment]
can u try 24.2.1

**Comment by drewburlingame** [comment]
updated and it still adds the new line.

![image](https://user-images.githubusercontent.com/103345/142642863-7e5b9ee4-667d-410f-a317-34098c748495.png)

**Comment by SimonCropp** [comment]
can you have a go at submitting a PR with a test that replicated this

**Comment by drewburlingame** [comment]
If I get time, I'll look into it.  I'll probably prioritize looking into the indent feature as I've already accepted the extra line in all the docs in CommandDotNet.
