### ISSUE TITLE
Indented snippets

### ISSUE THREAD

**Issue by drewburlingame** [SimonCropp/MarkdownSnippets#432]
#### Is the feature request related to a problem

using mkdocs, we can create tabbed content within a page using this syntax.

``` 
=== ".NET CLI"

    `dotnet add package CommandDotNet`

=== "Nuget Package Manager"

    `Install-Package CommandDotNet` 
```

The contents of the tab must be indented.  I was hoping if the initial snippet text was indented, then the inserted snippet would also be indented.  I started with

![image](https://user-images.githubusercontent.com/103345/142606981-e66f7137-23ab-4d9c-81fb-468a10d69558.png)

but mdsnippets didn't find the snippets because they're not at the beginning of the line.

#### Describe the solution

mdsnippets finds the indented snippet and indents the inserted snippet with the same number of indents.

Is this something you'd be interested in supporting and do you think it would be fairly simple?  I'm happy to help out if you're interested in the feature.

**Comment by SimonCropp** [comment]
yep happy to accept this as a feature. difficult to tell how much effort it would be

**Comment by SimonCropp** [comment]
bump

**Comment by drewburlingame** [comment]
Hi  @SimonCropp . I'm not going to get to this anytime soon.  I've just worked around it for now. Feel free to close it if you'd like. I'll come back to it if time allows.

**Comment by SimonCropp** [comment]
ok
