### ISSUE TITLE
Snippets in JSX static site generators

### ISSUE THREAD

**Issue by matkoch** [SimonCropp/MarkdownSnippets#453]
#### Is the feature request related to a problem

The default syntax of:

```
<!-- snippet: xyz -->
```

Won't work in JSX components. Instead it has to look something like this:

<img width="525" alt="JetBrains Rider-nuke-web – 06-versioning mdx-2022-01-30-3Jlei0gl" src="https://user-images.githubusercontent.com/5005566/151706491-a592e856-8463-4b07-bb75-69fa8e863064.png">

#### Describe the solution

- Markdown snippets would have to discover this new comment style `{/* snippet: xyz */}` in the place it should be included.
- Additionally, it would have to:
  -  Put `` {` `` at the start and `` `} `` at the end of the snippet and consider these the new code fences (instead of `` ``` ``)
  - Escape empty lines with `\n`

#### Describe alternatives considered

The alternative is not to use markdown snippets.

#### Additional context

No additional context.

**Comment by SimonCropp** [comment]
in what context are you using this? 

markdown snippets is specifically meant to produce valid markdown, it seems this use-case is not producing valid (or at least non standard) markdown? ie if that file is makrdown, shoundt the renderer properly convert ``` to your screenshot above?

Will you want o use thig from msbuild?

**Comment by matkoch** [comment]
Found a workaround, so no longer relevent.

**Comment by matkoch** [comment]
Four years later, this is coming back at me :)

Some updated information:
- This is being used in an mdx file which is processed by [fumadocs](https://www.fumadocs.dev).
- Originally, I was using another SSG, so this seems to be a general issue.
- Since you mentioned "valid markdown" – AFAIU, the official Markdown spec doesn't support comments. However, `<!-- .. -->` works for most parsers. For MDX files it looks fair to say, that another comment format needs to be used.
- Same as with #740 I'd be good to have just a delegate (not using CLI tool / MSBuild task).
- Files are going to be re-processed, so any approach that involves converting back and forth would be rather inconvenient.
