### ISSUE TITLE
Allow additional file extensions for markdown files

### ISSUE THREAD

**Issue by matkoch** [SimonCropp/MarkdownSnippets#455]
#### Is the feature request related to a problem

`.mdx` files are mostly like `.md` files with the exception that they also allow JSX to be used. Currently MarkdownSnippets only scans for `.md` files.

#### Describe the solution

Either another option could be added to specify user-relevant markdown files, or `.mdx` could be added hardcoded to the traversed types of files.

#### Describe alternatives considered

None

#### Additional context

None.

**Comment by SimonCropp** [comment]
should mdx be supported by includes https://github.com/SimonCropp/MarkdownSnippets/blob/main/docs/includes.md  ?

**Comment by matkoch** [comment]
you mean to reference the snippet in the md file and then include in mdx? i can try later, but even if, i'm sure the organizational effort would be a real pain

**Comment by matkoch** [comment]
Ah nevermind, includes don't work. I was looking at the wrong file.

**Comment by SimonCropp** [comment]
> rather cumbersome having to outsource dozens of snippets into their own files

it not about having snippets in their own files. it is about having a re-usable chunks of markdown that can be consumed by other markdown files

**Comment by matkoch** [comment]
i'm not sure what's the difference in the case I'm talking about. every snippet would have to go into its own `.include.md` file so that I can include it separately into `.mdx` ... but in any case – includes don't seem to work

**Comment by SimonCropp** [comment]
can u try 24.3.0-beta.1

**Comment by matkoch** [comment]
LGTM! :shipit:

**Comment by SimonCropp** [comment]
shipping now
