### ISSUE TITLE
Local link doesn't work when readme hosted elsewhere

### ISSUE THREAD

**Issue by distantcam** [SimonCropp/MarkdownSnippets#496]
I've started using MarkdownSnippets over on a new repo [AutoCtor](https://github.com/distantcam/AutoCtor) and wanted to reuse the readme generated for the NuGet package.

The problem is the links in the readme, at least for github, are missing the start of a full URL. I guess the assumption is the file would only be served from GItHub, so a relative link works then.

However I would also like to use that readme in the NuGet package, which can render markdown files from the package. https://docs.microsoft.com/en-us/nuget/nuget-org/package-readme-on-nuget-org

Would it be possible to change the link generation to make fully qualified links?

**Comment by distantcam** [comment]
Hmm, nevermind. Looks like nuget doesn't allow HTML in the readme anyway.

**Comment by SimonCropp** [comment]
doesnt it support markdown?
