### ISSUE TITLE
Consider syntax for one-line snippets

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#50]
#### Is the feature request related to a problem

Some of the ApprovalTests.cpp tests are becoming quite cluttered as a result of the MarkdownSnippets text.

For example (not yet updated to new start/end markers):

```c++
// startcode googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName1 )
// endcode
{
    ApprovalTestNamer namer;
// startcode googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
// endcode
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

A couple of times, I've come to work on a test file and all my brain has seen is the comments for MarkdownSnippets, and not the code...

#### Describe the solution

Would it be possible to have an extra kind of markup which is an inline, end-of-line comment.

For example:

```c++
TEST(TestCaseName_IgnoreThis, TestName2) // inline-snippet googletest_customize_test
{
    ApprovalTestNamer namer;
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName"; // inline-snippet googletest_customize_test_name
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

The idea is that the characters from `// snippet-inline` to the end of the line would be excluded from the output.

I realise that this is a complication for the current code, which does not need to understand how to write comments in all the different languages that someone might use this tool with...

#### Describe alternatives considered

One idea I can think of is for @isidore and I to add white-space around our markdown code blocks. This would change the top example to:

```c++
// startcode googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName1 )
// endcode

{
    ApprovalTestNamer namer;

// startcode googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
// endcode

    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

This works well for glance-ability of the second block - with `auto outputFileBaseName` - but any code-formatting tool would delete the blank line before the opening `{`, and I think separating the `TEST` and `{`  lines with a blank line is really jarring to read, for anyone familiar with the C++ Google Test framework.

Another is for us to indent some of the comments, so that they are consistent with the surroudning code, which does help a little - but I'd still prefer the inline idea...

```c++
// startcode googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName1 )
// endcode
{
    ApprovalTestNamer namer;
    // startcode googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
    // endcode
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

#### Additional context

Can't think of any.

**Comment by SimonCropp** [comment]
```
// startcode googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName1 )
// endcode
{
    ApprovalTestNamer namer;
    // startcode googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
    // endcode
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

that should work

**Comment by claremacrae** [comment]
That looks the same as the second alternative that I considered, just without formatting...

Ah - maybe I as unclear... 

In the alternatives section, what I meant to convey was "these are two things that Llewellyn and I could do already as workarounds, to improve the formatting of the example code I gave, to improve what we currently have....

But even after those edits, the code is still quite cluttered, and hence I'm suggesting an inline equivalent to be considered, for use with 1-line code snippets...

**Comment by isidore** [comment]
One idea would be to enforce comments to mirror the ending. So 
```cpp
TEST(TestCaseName_IgnoreThis, TestName2) // inline-snippet googletest_customize_test //
{
    ApprovalTestNamer namer;
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName"; // inline-snippet // googletest_customize_test_name
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

I think this would work in most languages  I am aware of  { except pascal }

``` python
fun TEST(TestCaseName_IgnoreThis, TestName2) # inline-snippet googletest_customize_test #
```

``` applescript
tell application "Finder" to close every window -- inline-snippet close_all -- 
```

**Comment by isidore** [comment]
Although I highly suggest the consistency of : 
so the above should have been:

One idea would be to enforce comments to mirror the ending. So 
```cpp
TEST(TestCaseName_IgnoreThis, TestName2) // inline-snippet: googletest_customize_test //
{
    ApprovalTestNamer namer;
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName"; // inline-snippet:  googletest_customize_test_name //
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

I think this would work in most languages  I am aware of  { except pascal }

``` python
fun TEST(TestCaseName_IgnoreThis, TestName2) # inline-snippet: googletest_customize_test #
```

``` applescript
tell application "Finder" to close every window -- inline-snippet: close_all -- 
```

**Comment by SimonCropp** [comment]
how about this?

```
// inline-snippet: googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName2)
{
    ApprovalTestNamer namer;
     // inline-snippet: googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

**Comment by claremacrae** [comment]
Interesting... Well, it's an improvement over a pair of lines, but it's confusing as it isn't inline... (on the same line)

How about `oneline-snippet` snippet instead:

```c++
// oneline-snippet: googletest_customize_test
TEST(TestCaseName_IgnoreThis, TestName2)
{
    ApprovalTestNamer namer;
    // oneline-snippet: googletest_customize_test_name
    auto outputFileBaseName = "GoogleFixtureNamerCustomizationTests.TestName";
    EXPECT_EQ(namer.getOutputFileBaseName(), outputFileBaseName);
}
```

**Comment by SimonCropp** [comment]
i have to say, i am not sure this feature reaches the level of justifiable return on investment.

it effectively saves one line of code per snippet.

and i know the original request was to have the `inline-snippet` at the end of the line, but this decreases readability and disocvereablity of "this is a snippet" by placing it at a random horizontal location

**Comment by claremacrae** [comment]
Hi Simon,

That's fine - I'm really happy to go with your recommendation - and certainly I now realise can pay more attention to format our comments a bit more tidily.

I'm really happy if you want to just go ahead and close this ticket...

**Comment by SimonCropp** [comment]
sorry peoples. closing this one
