### ISSUE TITLE
Possiblity to include markdown files

### ISSUE THREAD

**Issue by OskarKlintrot** [SimonCropp/MarkdownSnippets#518]
#### Is the feature request related to a problem

I'm trying to switch from `SourceTransform` to `InPlaceOverwrite` but I ran into an issue. `ValidateContent` now errors out on some markdown files I'm not interested in (some README.md for test projects etc). I'm only interested for MarkdownSnippets to work it's magic on the md-files in `\Docs\DocFx\articles` but still looking for snippets in `\`. There are some md-files here and there making it a bit cumbersome to exclude them all.

#### Describe the solution

```"IncludeMarkdownDirectories": [ "\\Docs\\DocFx\\articles" ]```

#### Describe alternatives considered

```"ExcludeMarkdownDirectories": [ "A", "Whole", "Bunch", "Of", "Directories" ]```

#### Additional context

~~I'm not sure what #120 is but it sounds like it could be this. That feature seems to have been removed.~~ Nope, [it wasn't](https://github.com/SimonCropp/MarkdownSnippets/tree/6884a55ea011eb5c62b2898e38c4367deaa53d5f#markdown-includes).

**Comment by SimonCropp** [comment]
can u share a failing unit test as a Pull Request

**Comment by OskarKlintrot** [comment]
Sure, just give me a few days!
