### ISSUE TITLE
Mark output files readonly

### ISSUE THREAD

**Issue by JayBazuzi** [SimonCropp/MarkdownSnippets#52]
#### Is the feature request related to a problem?

Often while iterating on documentation, we accidentally edit the output files instead of the source files. These edits then get wiped out when we rerun mdsnippets.

#### Describe the solution

mdsnippets could mark the output files to be writable before writing them, and set them back to readonly right after.

#### Describe alternatives considered

None at this time.

#### Additional context

We're on Windows. 

Thanks, 
- Jay and Llewellyn

**Comment by claremacrae** [comment]
I really like this idea.

**Comment by SimonCropp** [comment]
Is it safe to mark files under source control as read only? Couldn’t this potentially interfere with the source control tooling?

**Comment by SimonCropp** [comment]
https://github.com/SimonCropp/MarkdownSnippets#mark-resulting-files-as-read-only

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
