### ISSUE TITLE
Tests fail on Mac

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#538]
#### Describe the bug

Cloning the project on Mac and running the tests gives a number of failures, some of which seem to be caused by the approved files containing windows `\` separators, but the Mac generating '/' separators.

I have not found a way to get a list of failing tests to past here.

Here is the console output of one example:

```diff
VerifyException: Directory: /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/src/Tests/Console

VerifyException
Directory: /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/src/Tests/Console
NotEqual:
  - Received: CommandRunnerTests.TargetDirectoryLong.received.txt
    Verified: CommandRunnerTests.TargetDirectoryLong.verified.txt

FileContent:

NotEqual:

Received: CommandRunnerTests.TargetDirectoryLong.received.txt
Verified: CommandRunnerTests.TargetDirectoryLong.verified.txt
Compare Result:
  {
-   targetDirectory: {ProjectDirectory}bin\,
+   targetDirectory: {ProjectDirectory}bin/,
    configInput: {}
  }


  Exception doesn't have a stacktrace
```

20 tests fail.

Commit ID of this project: a068185782b991eb0b85017d87f9d7624ceec807
dotnet --version: 7.0.100
Rider version: JetBrains Rider 2022.3
Build #RD-223.7571.232, built on December 5, 2022

#### Minimal Repro

- Open the repo in an IDE on Mac (or, I presume, Linux)
- Run the Tests project

#### Submit a PR that fixes the bug

Llewellyn kindly had a go at adding a scrubber to convert `/` to `\`, but it then failed in a different way. (It no longer replaced the absolute path with some indicative variable name)

**Comment by claremacrae** [comment]
I would be happy to pair on this, if it would help for you to have access to a Mac machine.

**Comment by SimonCropp** [comment]
test now pass on mac

**Comment by claremacrae** [comment]
Confirmed. All passing now. Thank you.
