### ISSUE TITLE
Add Table Of Contents support

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/MarkdownSnippets#64]
https://github.com/SimonCropp/MarkdownSnippets#table-of-contents

**Comment by claremacrae** [comment]
As a possible example:

In ApprovalTests.cpp we use this:
https://www.npmjs.com/package/doctoc

And we run it with this:
`doctoc --title **Contents** *.md build/ doc/`

**Comment by claremacrae** [comment]
I haven't managed to get that `*.md` approach to work on windows, and so I run it in cygwin, and line endings get messed up - so having it built in to mdsnippets would be much appreciated...

I'd been wanting to ask if you could add a ToC to mdsnippets' home page too - so I guess this would help with that! :-)

**Comment by SimonCropp** [comment]
@claremacrae still in a beta release. but here is a first cut of the doco https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/table-of-contents.md#table-of-contents

**Comment by claremacrae** [comment]
@SimonCropp Thanks! I notice that there's a start-tag for the generated TOC but not an end one...

I was thinking an end one would be useful, mainly for consistency.

**Comment by claremacrae** [comment]
We've found it useful to go for deeper ToC than just level 2:

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/UsingGoogleTests.md#top

**Comment by SimonCropp** [comment]
> I notice that there's a start-tag for the generated TOC but not an end one

fixed

**Comment by SimonCropp** [comment]
hows this https://github.com/SimonCropp/MarkdownSnippets#heading-level
