### ISSUE TITLE
remove static method DirectoryMarkdownProcessor.RunForFilePath

### ISSUE THREAD

**Issue by SimonCropp** [SimonCropp/MarkdownSnippets#66]
use instance API instead

**Comment by SeanFeldman** [comment]
I'm a bit late to update and have a question about this change.
Static API did not require specifying any parameters. Instance API now has a mandatory target directory that cannot be null or empty. What's the expected target directory to ensure unit tests continue working properly?

**Comment by SimonCropp** [comment]
What repo r u using it in?

**Comment by SeanFeldman** [comment]
https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin.
Test: https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/blob/3777933288ee39d53909df2adcd0975f58a16daf/src/ServiceBus.AttachmentPlugin.Tests/DocoUpdater.cs

**Comment by SeanFeldman** [comment]
I need to use `GitRepoDirectoryFinder.FindForFilePath()`.

When you change APIs similar to this one, would be good to provide a hint of what needs to be used. I couldn't find anything related to this in readme.md and had to scan the tests to find out what would work. Thanks.

**Comment by SimonCropp** [comment]
https://github.com/SeanFeldman/ServiceBus.AttachmentPlugin/pull/137

**Comment by SimonCropp** [comment]
>  would be good to provide a hint of what needs to be used. 

sounds good. can u submit a docs PR to [this page](https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/api.md) that explains the use of GitRepoDirectoryFinder
