### ISSUE TITLE
Support Providing Languages for Code Blocks that differ from File Extensions

### ISSUE THREAD

**Issue by khalidabuhakmeh** [SimonCropp/MarkdownSnippets#687]
#### Is the feature request related to a problem

Currently, the language blocks use the file extension of the file. This issue can be because the rendering language block may not match the file extension. A good example is a Blazor component, which may include `razor` and `csharp` languages within a single file. 

#### Describe the solution

Allow users to specify the language as either a general map in the `mdsnippets.json` file to support a general map for file extensions.

```json
{
  "$schema": "https://raw.githubusercontent.com/SimonCropp/MarkdownSnippets/master/schema.json",
  "Convention": "InPlaceOverwrite",
  "LinkFormat": "None",
  "Languages" : {
    "cs" : "csharp",
    "cshtml" : "razor"
  }
}
```

Additionally, snippets could define them inline.

```csharp
// begin-snippet(language=csharp): HelloWorld
Console.WriteLine("Hello, Matt!");
// end-snippet
```

#### Describe alternatives considered

Modify the code blocks after MarkdownSnippets has run.

#### Additional context

https://github.com/SimonCropp/MarkdownSnippets/blob/2c8bea83bf36b97faa9390c356dcfa4742adf359/src/MarkdownSnippets/Processing/MarkdownProcessor.cs#L343-L359

**Comment by SimonCropp** [comment]
would it be better to rename LinkFormat to Hosting
https://github.com/SimonCropp/MarkdownSnippets#linkformat

and then hard code the file extension to language map?

**Comment by khalidabuhakmeh** [comment]
That doesn't sound like a bad idea.

**Comment by SimonCropp** [comment]
list of GH languages https://github.com/github-linguist/linguist/blob/master/lib/linguist/languages.yml

**Comment by khalidabuhakmeh** [comment]
👋 Hello. Just saying hello :)

**Comment by SimonCropp** [comment]
i am not going to get around to "the full correct implementation"

how about you submit a PR that meets your requirements?

**Comment by khalidabuhakmeh** [comment]
Honestly I forget what I was asking for in the first place. I was seriously just saying Hello :)

We can close this issue for now. If it comes up again I might take a stab at it.
