### ISSUE TITLE
Not all directories and files starting with a period are ignored

### ISSUE THREAD

**Issue by ValdisThomann** [SimonCropp/MarkdownSnippets#705]
#### Describe the bug

"All directories and files starting with a period" are not currently being ignored by default, contrary to: https://github.com/SimonCropp/MarkdownSnippets/blob/main/docs/exclusion.md#ignored-paths

I was expecting that any directory starting with a `.` should be ignored from snippet and markdown scanning by default. Currently, this behaviour seems to be limited to:
```
.git
.vs
.idea
```

#### Minimal Repro

1. Create a directory called `.somearbitrarypathwithfullstop`
2. Add a file to this directory, and add snippet comments to this file
3. Run `mdsnippets` in the context of the parent of the directory created in step 1
4. Note that the log will show snippets extracted from `.somearbitrarypathwithfullstop`

#### Submit a PR that fixes the bug

See PR for proposed fix, along with breaking unit tests: #704

**Comment by SimonCropp** [comment]
alternative https://github.com/SimonCropp/MarkdownSnippets/pulls
