### ISSUE TITLE
Table of contents links don't work for headings with commas

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#71]
#### Describe the bug

```markdown

toc

## I am a title, but it has a comma
```

The table of contents generated from this will not work - i.e. clicking on the link in the toc does not cause Firefox to jump to the location, when viewing the generated file on github.

#### Minimal Repro

As above.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
