### ISSUE TITLE
Toggle Links From Output Results

### ISSUE THREAD

**Issue by khalidabuhakmeh** [SimonCropp/MarkdownSnippets#713]
#### Is the feature request related to a problem

I am using MarkdownSnippets in a different documentation system with its link system, and I would like to disable links, including the anchors entirely from the output. 

#### Describe the solution

Disable all links from the output of the snippets, including the source control and anchor links.

````markdown 
<!-- snippet: App:HelloWorld -->
<a id='snippet-App:HelloWorld'></a>
```cs
// Program.cs
Console.WriteLine("Hello, Again!");
```
<sup><a href='#snippet-App:HelloWorld' title='Start of snippet'>anchor</a></sup>
<!-- endSnippet -->
````

this would be converted to

````markdown
<!-- snippet: App:HelloWorld -->
```cs
// Program.cs
Console.WriteLine("Hello, Again!");
```
<!-- endSnippet -->
````

This could be toggled via a flag or by a `mdsnippets.json` value of `EnableLinks`.

#### Additional context

The documentation system is Astro Starlight.

**Comment by SimonCropp** [comment]
isnt that achieved by omitsnippetlinks  ?

https://github.com/SimonCropp/MarkdownSnippets?tab=readme-ov-file#omitsnippetlinks

**Comment by khalidabuhakmeh** [comment]
Oh it is. I scanned the docs several times. Not sure how I missed that. Apologies.

**Comment by SimonCropp** [comment]
no apologies necessary.
