### ISSUE TITLE
mdsnippets on Mac produces files with mixed line endings, confusing GitHub Desktop

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#88]
#### Preamble

This has happened on both @isidore and my Macs.

Versions on my machine:

* Tool 'markdownsnippets.tool' was reinstalled with the latest stable version (version '16.4.0').
* .NET Core SDK 2.2.401 (x64)

#### Describe the bug

Expected behaviour: The output .md files should have consistent line endings

Actual behaviour: On Mac, when the input file has Unix EOLs, the output file has the following lines with different EOLs:

```markdown
<!-- toc -->
## Contents

```

I'll attach a screenshot diffing the source and destination files in BeyondCompare, as it makes it easy to see diffs in line endings.

When I run mdsnippets on files in https://github.com/approvals/ApprovalTests.cpp, there are always some files whose source has not changed, but whose generated files show a few lines of difference in GitHub Desktop, around the table of contents.

#### Minimal Repro

Example file to run it on:

https://github.com/approvals/ApprovalTests.cpp/blob/master/doc/mdsource/TemplatePage.source.md

Download that to a Mac and convert it with this command line:

```bash
mdsnippets --exclude cmake-build --toc-level 5 --readonly true --header "GENERATED FILE - DO NOT EDIT\nThis file was generated by [MarkdownSnippets](https://github.com/SimonCropp/MarkdownSnippets).\nSource File: {relativePath}\nTo change this file edit the source file and then execute ./run_markdown_templates.sh."
```

View the output file with an editor that shows line endings. You should see that 3 lines have different EOLs.

**Comment by claremacrae** [comment]
BeyondCompare Screenshot showing the problem lines marked in black rectangle, and this inconsistent line endings in red:

<img width="1439" alt="Screenshot 2019-08-31 at 21 33 36 copy" src="https://user-images.githubusercontent.com/4840096/64069026-2a83e580-cc39-11e9-91d3-730806784a06.png">

**Comment by claremacrae** [comment]
The reason this is a problem is that when I run mdsnippets with only one source file changed, both GitHub and CLion will show a random number of other generated files as changed, and it's tedious reverting these TOC lines in each one.

I do wonder whether the absence of a git eol policy in this repo might contribute to this - in that maybe our source files have got a messy mix of line endings - but the problem occurs in files where the source eols are consistent and native.

**Comment by claremacrae** [comment]
Currently GitHub and CLion show only these files as changed after running mdnsippets (using the command line args given at the end of https://github.com/approvals/ApprovalTests.cpp/blob/master/run_markdown_templates.sh)

```text
doc/Contributing.md
doc/CustomComparators.md
doc/MultipleOutputFilesPerTest.md
doc/UsingCatch.md
README.md
```

No idea why these are significant.

The current changet I'm using is:

https://github.com/approvals/ApprovalTests.cpp/commit/deebc8a4dbc36a3a2b828bc4a5021f4a4d5b5a5c

**Comment by claremacrae** [comment]
Thank you!

**Comment by SimonCropp** [comment]
did it work?

**Comment by claremacrae** [comment]
Yes it did!

https://github.com/approvals/ApprovalTests.cpp/commit/c669aa99c1e57b3adba690fee1fc279beeb498b9

**Comment by claremacrae** [comment]
Shhh: I'm doing a Lightning Talk plugging mdsnippets at CppCon the week after next, so having this working well on the Mac I'll have with me really helps!
