### ISSUE TITLE
Level 4, 5 and 6 headings in TOC have incorrect text and anchor

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#89]
#### Preamble

version: latest stable version (version '16.4.1').

#### Describe the bug

Headings in levels 4, 5 and 6 are displayed in the ToC with 1, 2 and 3 extra `#` prefixes.

They are also not given unique anchors, if the heading text is duplicated.

#### Minimal Repro

**Input:**

```text
# Title

toc

## Section

### Section

#### Section 

##### Section 

###### Section
```

**Command line used**

From https://github.com/approvals/ApprovalTests.cpp/blob/b802c36bf5886745f76ab7b143eb6ab1eb706c9f/run_markdown_templates.sh:

```bash
mdsnippets \
    --exclude cmake-build \
    --toc-level 5 \
    --readonly true \
    --header "GENERATED FILE -...  execute ./run_markdown_templates.sh."
```

**Expected TOC in Output:**

```text
<!-- toc -->
## Contents

  * [Section](#section)
    * [Section](#section-1)
      * [Section](#section-2)
        * [Section](#section-3)
          * [Section](#section-4)
<!-- endtoc -->
```

**Actual TOC in Output:**

```text
<!-- toc -->
## Contents

  * [Section](#section)
    * [Section](#section-1)
      * [# Section](#-section)
        * [## Section](#-section)
          * [### Section](#-section)
<!-- endtoc -->
```

Note that there are 3 sections with anchor '-section'..

PS readonly saved me at least twice, editing the repro for this ticket - thanks!

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.

**Comment by claremacrae** [comment]
Thanks Simon - confirmed fixed...
